spring:
  datasource:
    url: jdbc:h2:mem:inditexdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql: off
    org.springframework.test.context.support: warn
